const locations = [
    {
        location_name: "Old Pale",
        street: "Delamere Forest",
        town: "Delamere",
        region: "North West",
        postcode: "CW8 2HZ",
        location_description: "Using forest gravelled tracks and purpose-built stoned paths up the hill you will be rewarded by enormous skies and an endless view. There are plenty of benches along the route to encourage you to stop and take it all in. With hourly trains from Manchester and Chester, Delamere Forest and the Old Pale walk is a great place to explore at any time of year.",
        category_seaside: false,
        category_castles: false,
        category_caves: false,
        category_peaceful: true,
        category_hiking: false,
        category_hills: true,
        category_historic: false,
        category_secluded: true,
        category_casual: true,
        category_lakes: false,
        category_busy: false,
        category_woods: true,
        amenities_parking: true,
        amenities_food: true,
        amenities_family: true,
        amenities_changing_facilities: false,
        amenities_disability_access: true,
        amenities_peaceful: true,
        amenities_electric_charging: false,
        amenities_no_restaurants: false,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: false,
        amenities_pet_friendly: true,
        amenities_forests: false,
        amenities_lots_of_wildlife: true,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: false,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: true,
        amenities_public_transport_bad: false,
        amenities_accommodation: false,
        amenities_wifi: false,
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1659962631/untrodden-pics/old_pale_rwsbbp.jpg",
        latitude:  53.22376473032904, 
        longitude: -2.6849296015820943,
        user_email: "untroddensoc@gmail.com"
    },
    {
        location_name: "Dunnottar Castle",
        street: "Dunnottar Castle",
        town: "Stonehaven",
        region: "North East Scotland",
        postcode: "AB39 2TL",
        location_description: "Dunnottar Castle is a dramatic and evocative ruined cliff top fortress which was the home of the Earls Marischal, once one of the most powerful families in Scotland. Steeped in history, this romantic and haunting ruin is a photographer's paradise, a history lovers dream and an iconic tourist destination for visitors the world over. Visit Dunnottar Castle for your own unforgettable experience and discover the importance of Dunnottar - an impregnable fortress that holds many rich secrets of Scotland's colourful past.",
        category_seaside: true,
        category_castles: true,
        category_caves: false,
        category_peaceful: true,
        category_hiking: true,
        category_hills: true,
        category_historic: true,
        category_secluded: true,
        category_casual: true,
        category_lakes: false,
        category_busy: false,
        category_woods: false,
        amenities_parking: true,
        amenities_food: true,
        amenities_family: true,
        amenities_changing_facilities: true,
        amenities_disability_access: true,
        amenities_peaceful: true,
        amenities_electric_charging: false,
        amenities_no_restaurants: false,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: true,
        amenities_pet_friendly: true,
        amenities_forests: false,
        amenities_lots_of_wildlife: false,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: true,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: true,
        amenities_public_transport_bad: false,
        amenities_accommodation: false,
        amenities_wifi: false,
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1659962631/untrodden-pics/dunnottar_castle_fm0vft.jpg",
        latitude:  56.945395623234326, 
        longitude: -2.1978927412285247,
        user_email: "untroddensoc@gmail.com"
    },
    {
        location_name: "Symonds Yat",
        street: "",
        town: "Symonds Yat",
        region: "West Midlands",
        postcode: "HR9",
        location_description: "Symonds Yat is a village in the Wye Valley and a popular tourist destination, straddling the River Wye in the English county of Herefordshire, close to the Gloucestershire border. It is within a few miles of Monmouthshire and the Welsh border.",
        category_seaside: false,
        category_castles: false,
        category_caves: false,
        category_peaceful: true,
        category_hiking: true,
        category_hills: true,
        category_historic: false,
        category_secluded: false,
        category_casual: true,
        category_lakes: true,
        category_busy: false,
        category_woods: true,
        amenities_parking: true,
        amenities_food: true,
        amenities_family: true,
        amenities_changing_facilities: true,
        amenities_disability_access: true,
        amenities_peaceful: true,
        amenities_electric_charging: true,
        amenities_no_restaurants: false,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: true,
        amenities_pet_friendly: true,
        amenities_forests: true,
        amenities_lots_of_wildlife: true,
        amenities_watersports: true,
        amenities_shopping: true,
        amenities_bodies_of_water: true,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: true,
        amenities_public_transport_bad: false,
        amenities_accommodation: true,
        amenities_wifi: true,
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1659962631/untrodden-pics/symonds_yat_aymseo.jpg",
        latitude: 51.84645761540501,
        longitude: -2.6461539072289497,
        user_email: "untroddensoc@gmail.com"
    },
    {
        location_name: "Foggintor Quarry",
        street: "Foggintor Quarry",
        town: "Yelverton",
        region: "South West",
        postcode: "PL20 6SS",
        location_description: "For more than a hundred years, Foggintor Quarry was one of three great Dartmoor granite quarries, providing the stone for famous landmarks.",
        category_seaside: false,
        category_castles: false,
        category_caves: false,
        category_peaceful: true,
        category_hiking: true,
        category_hills: true,
        category_historic: true,
        category_secluded: true,
        category_casual: true,
        category_lakes: true,
        category_busy: false,
        category_woods: true,
        amenities_parking: true,
        amenities_food: false,
        amenities_family: true,
        amenities_changing_facilities: false,
        amenities_disability_access: false,
        amenities_peaceful: true,
        amenities_electric_charging: false,
        amenities_no_restaurants: true,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: true,
        amenities_pet_friendly: true,
        amenities_forests: true,
        amenities_lots_of_wildlife: true,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: true,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: false,
        amenities_public_transport_bad: true,
        amenities_accommodation: false,
        amenities_wifi: false,
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1659962632/untrodden-pics/foggintor_quarry_gsjnkd.jpg",
        latitude: 50.54478107930167,
        longitude: -4.024222293115765,
        user_email: "untroddensoc@gmail.com"
    },
    {
        location_name: "Solomon's Tower",
        street: "Green Lane",
        town: "Buxton",
        region: "East Midlands",
        postcode: "SK17 9DH",
        location_description: "Solomon's Temple, also known as Grin Low Tower, is a Victorian fortified hill marker at the summit of Grin Low Hill near the spa town of Buxton. At 439 metres above sea-level, the views from the top of this modest tower are not-to-be-missed and on a clear day it's possible to see Mam Tor in Castleton and Kinder Scout - the highest point in the Peak District!",
        category_seaside: false,
        category_castles: true,
        category_caves: false,
        category_peaceful: true,
        category_hiking: true,
        category_hills: true,
        category_historic: true,
        category_secluded: true,
        category_casual: true,
        category_lakes: false,
        category_busy: false,
        category_woods: true,
        amenities_parking: true,
        amenities_food: false,
        amenities_family: true,
        amenities_changing_facilities: false,
        amenities_disability_access: false,
        amenities_peaceful: true,
        amenities_electric_charging: false,
        amenities_no_restaurants: true,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: true,
        amenities_pet_friendly: true,
        amenities_forests: true,
        amenities_lots_of_wildlife: true,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: false,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: true,
        amenities_public_transport_bad: false,
        amenities_accommodation: false,
        amenities_wifi: false,
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1659962630/untrodden-pics/solomons_tower_umzn1w.jpg",
        latitude: 53.242709,
        longitude: -1.920569,
        user_email: "untroddensoc@gmail.com"
    },
    {
        location_name: "Marchmont Community Garden",
        street: "Marchmont Street",
        town: "London",
        region: "London",
        postcode: "WC1N 1NJ",
        location_description: "This is a pocket park in Bloomsbury next to the Brunswick Centre that was once a private garden and fenced off, but just over a decade ago was opened up as a public space.",
        category_seaside: false,
        category_castles: false,
        category_caves: false,
        category_peaceful: true,
        category_hiking: false,
        category_hills: false,
        category_historic: false,
        category_secluded: true,
        category_casual: true,
        category_lakes: false,
        category_busy: false,
        category_woods: false,
        amenities_parking: false,
        amenities_food: true,
        amenities_family: true,
        amenities_changing_facilities: false,
        amenities_disability_access: true,
        amenities_peaceful: true,
        amenities_electric_charging: false,
        amenities_no_restaurants: false,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: false,
        amenities_pet_friendly: true,
        amenities_forests: false,
        amenities_lots_of_wildlife: false,
        amenities_watersports: false,
        amenities_shopping: true,
        amenities_bodies_of_water: false,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: true,
        amenities_public_transport_bad: false,
        amenities_accommodation: false,
        amenities_wifi: false,
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1659962638/untrodden-pics/marchmont_garden_lkoh4o.jpg",
        latitude: 51.525098,
        longitude: -0.124815,
        user_email: "untroddensoc@gmail.com"
    },
    {
        location_name: "Harborne Walkway",
        street: "Harborne Walkway",
        town: "Birmingham",
        region: "West Midlands",
        postcode: "B16 0SL",
        location_description: "The Harborne Walkway is a 1.5 mile stretch which runs from Forest Drive and Park Hill Road Harborne entrances to Summerfield Park. It is a linear park and the responsibility of the Council Parks Department. It passes by allotments and the Harborne Bird Sanctuary following the old railway line. It’s a nice atmospheric stroll with shady woodland, embankments, wide verges and across or under 6 bridges. The path is well surfaced and forms part of an easy route, safe for cyclists and walkers, which carries on into Summerfield Park.",
        category_seaside: false,
        category_castles: false,
        category_caves: false,
        category_peaceful: true,
        category_hiking: true,
        category_hills: false,
        category_historic: false,
        category_secluded: true,
        category_casual: true,
        category_lakes: false,
        category_busy: false,
        category_woods: true,
        amenities_parking: false,
        amenities_food: false,
        amenities_family: true,
        amenities_changing_facilities: false,
        amenities_disability_access: true,
        amenities_peaceful: true,
        amenities_electric_charging: false,
        amenities_no_restaurants: true,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: true,
        amenities_pet_friendly: true,
        amenities_forests: true,
        amenities_lots_of_wildlife: true,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: false,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: true,
        amenities_public_transport_bad: false,
        amenities_accommodation: false,
        amenities_wifi: false,
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1659962640/untrodden-pics/harborne_walkway_i8kuqh.jpg",
        latitude: 52.481151,
        longitude: -1.943754,
        user_email: "untroddensoc@gmail.com"
    },
    {
        location_name: "Horgabost Beach",
        street: "Horgabost",
        town: "Isle of Harris",
        region: "Outer Hebrides",
        postcode: "HS3 3HR",
        location_description: "Horgabost is yet another stunning white sandy Hebridean beach. Located on South Harris, this beach is just around the corner from better known Luskentyre beach. Horgabost shares the same crystal clear green blue water and pristine sands but is slightly more sheltered. The beach looks straight out over the Sound of Taransay with the mountains beyond forming a spectacular backdrop. It is from Horgabost that you can take a boat trip out into the sound. Like other Harris Isle beaches the meadows leading down to the coast become carpeted in wildflowers during the summer months. This is known as ‘machair’ locally. Whilst there are no facilities on the beach per se, there is a campsite within a stone’s throw with a shop and toilets.",
        category_seaside: true,
        category_castles: false,
        category_caves: false,
        category_peaceful: true,
        category_hiking: false,
        category_hills: false,
        category_historic: false,
        category_secluded: true,
        category_casual: true,
        category_lakes: false,
        category_busy: false,
        category_woods: false,
        amenities_parking: true,
        amenities_food: false,
        amenities_family: true,
        amenities_changing_facilities: false,
        amenities_disability_access: false,
        amenities_peaceful: false,
        amenities_electric_charging: false,
        amenities_no_restaurants: true,
        amenities_museums: false,
        amenities_beach: true,
        amenities_hiking: false,
        amenities_pet_friendly: true,
        amenities_forests: false,
        amenities_lots_of_wildlife: false,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: false,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: false,
        amenities_public_transport_bad: true,
        amenities_accommodation: false,
        amenities_wifi: false,
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1659962629/untrodden-pics/horgabost_beach_tox6yr.jpg",
        latitude: 57.86451376037841,
        longitude: -6.985501206854588,
        user_email: "untroddensoc@gmail.com"
    },
    {
        location_name: "Radnor Castle Mound",
        street: "11 High St, New Radnor",
        town: "Presteigne",
        region: "Mid Wales",
        postcode: "LD8 2SL",
        location_description: "An old castle mound in the Welsh hills. Radnor (Welsh: Maesyfed) is a village in Powys, Wales, to the south of Radnor Forest, and was the county town of Radnorshire. Attractions in the town include a significant castle [1] mound of a Norman motte [2]. New Radnor castle was originally called Trefaesyfed and was once a considerable fortress and a significant border castle in the Welsh Marches and played its part in the turmoil, violence and barbarity of the early medieval period typical of such a site.",
        category_seaside: false,
        category_castles: true,
        category_caves: false,
        category_peaceful: false,
        category_hiking: false,
        category_hills: false,
        category_historic: false,
        category_secluded: false,
        category_casual: false,
        category_lakes: false,
        category_busy: false,
        category_woods: false,
        amenities_parking: true,
        amenities_food: false,
        amenities_family: true,
        amenities_changing_facilities: false,
        amenities_disability_access: false,
        amenities_peaceful: true,
        amenities_electric_charging: false,
        amenities_no_restaurants: true,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: true,
        amenities_pet_friendly: true,
        amenities_forests: false,
        amenities_lots_of_wildlife: false,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: false,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: false,
        amenities_public_transport_bad: true,
        amenities_accommodation: false,
        amenities_wifi: false,
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1659962631/untrodden-pics/radnor_castle_mound_ft8poh.jpg",
        latitude: 52.24158189495012,
        longitude: -3.1556172471674757,
        user_email: "untroddensoc@gmail.com"
        
    },
    {
        location_name: "Glenoe Waterfall",
        street: "Waterfall Rd",
        town: "Gleno",
        region: "Antrim",
        postcode: "BT40 3LE",
        location_description: "Glenoe is a magnificent 30 foot waterfall nestling in the glens of Antrim and owned by the National Trust. It is such a charming place and I can’t believe that we did not know of its existence. Th walk up the narrow path up through the glen is superb (although you will definitely need walking boots and moderate fitness as it is steep enough). It is worth calling by though just to stroll over to the waterfall – this is a short level path and you will definitely want to take some photos. We visited in early March – magical greens – lots of mosses and ferns. Birds song added to the atmosphere. A perfect starter to a day in the Antrim glens. ",
        category_seaside: false,
        category_castles: false,
        category_caves: false,
        category_peaceful: true,
        category_hiking: true,
        category_hills: true,
        category_historic: false,
        category_secluded: true,
        category_casual: true,
        category_lakes: false,
        category_busy: false,
        category_woods: true,
        amenities_parking: false,
        amenities_food: false,
        amenities_family: true,
        amenities_changing_facilities: false,
        amenities_disability_access: false,
        amenities_peaceful: true,
        amenities_electric_charging: false,
        amenities_no_restaurants: true,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: true,
        amenities_pet_friendly: true,
        amenities_forests: true,
        amenities_lots_of_wildlife: true,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: false,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: true,
        amenities_public_transport_bad: false,
        amenities_accommodation: false,
        amenities_wifi: false,
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1659962630/untrodden-pics/glenoe_waterfall_nqqgpg.jpg",
        latitude: 54.799441382524805,
        longitude: -5.832403748657128,
        user_email: "untroddensoc@gmail.com"
    },
    {
        location_name: "Coney Island",
        street: "Kinnego Marina",
        town: "Oxford island",
        region: "Armagh",
        postcode: "BT66 6N",
        location_description: "Lying 1km off shore from Maghery Country Park, this island is an exciting destination to be explored. The island has a rich history spanning many centuries, with evidence of human occupation dating back 8000 years BC. One of the most westerly outposts of the Normans during their occupation of Ireland from 12th Century. The island is owned by the National Trust. Regular Boat Trips are no longer available due to passenger boats being unable to dock at Maghery Country Park. Pre-booked groups of 6-12 persons can avail of a boat trip from Kinnego Marina, May to August weather permitting on a Wednesday, Thursday or Friday morning only. This is a 3 hour round trip and booking is essential.",
        category_seaside: false,
        category_castles: false,
        category_caves: false,
        category_peaceful: true,
        category_hiking: false,
        category_hills: false,
        category_historic: true,
        category_secluded: true,
        category_casual: true,
        category_lakes: false,
        category_busy: false,
        category_woods: true,
        amenities_parking: false,
        amenities_food: false,
        amenities_family: true,
        amenities_changing_facilities: false,
        amenities_disability_access: false,
        amenities_peaceful: true,
        amenities_electric_charging: false,
        amenities_no_restaurants: true,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: false,
        amenities_pet_friendly: true,
        amenities_forests: true,
        amenities_lots_of_wildlife: true,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: true,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: false,
        amenities_public_transport_bad: true,
        amenities_accommodation: false,
        amenities_wifi: false,
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1659962628/untrodden-pics/coney_island_w3gcu8.jpg",
        latitude: 54.51692011833266,
        longitude: -6.550751071994922,
        user_email: "untroddensoc@gmail.com"
    },
    {
        location_name: "Swanage beach",
        street: "1 Shore Road",
        town: "Swanage",
        region: "West Midlands",
        postcode: "BH19 1L",
        location_description: "The sandy beach is one of the main attractions of the town. The waters are clean, and the beach has won many European Blue Flag Awards, as well as the Seaside Award. Swanage beach has a well earned reputation for being a good place to soak up the sun and play in the sand and sea.\n\nDeck chairs are available for hire, as are pedaloes, kayaks and sun beds. The beach runs the length of the town and is backed by a promenade lined with amusements and attractions. It is found on the South West Coast Path.\n\nDiver training and excursions run regularly from Swanage. Other water sports include sailing, water-skiing and wind surfing.\n\nAn attractive promenade (which is partly pedestrianised during the summer months) runs along a stretch of the beach.\n",
        category_seaside: true,
        category_castles: false,
        category_caves: false,
        category_peaceful: false,
        category_hiking: true,
        category_hills: false,
        category_historic: false,
        category_secluded: false,
        category_casual: false,
        category_lakes: false,
        category_busy: false,
        category_woods: false,
        amenities_parking: true,
        amenities_food: false,
        amenities_family: false,
        amenities_changing_facilities: false,
        amenities_disability_access: false,
        amenities_peaceful: false,
        amenities_electric_charging: false,
        amenities_no_restaurants: false,
        amenities_museums: true,
        amenities_beach: false,
        amenities_hiking: false,
        amenities_pet_friendly: false,
        amenities_forests: false,
        amenities_lots_of_wildlife: false,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: false,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: false,
        amenities_public_transport_bad: false,
        amenities_accommodation: false,
        amenities_wifi: false,
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1659962998/untrodden-pics/swanage_beach_ih9ppi.jpg",
        latitude: 52.489471,
        longitude: -2.898575,
        user_email: "untroddensoc@gmail.com"
    },
    {
        location_name: "Lickey Hills",
        street: "Warren Ln, Rednal, Birmingham",
        town: "Birmingham",
        region: "West Midlands",
        postcode: "B45 8ER",
        location_description: "Lovely woods with a beautiful view of Birmingham. Originally donated to Birmingham council by The Cadbury brothers to preserve Birmingham's woods and green spaces. Good parking and a visitors centre with toilets and a café. Large woodlands with hills, paths and a kids playground.\n\nGood public transport links and a couple of pubs nearby if you want to hydrate after a long walk!",
        category_seaside: false,
        category_castles: false,
        category_caves: false,
        category_peaceful: true,
        category_hiking: false,
        category_hills: true,
        category_historic: true,
        category_secluded: true,
        category_casual: true,
        category_lakes: false,
        category_busy: false,
        category_woods: true,
        amenities_parking: false,
        amenities_food: false,
        amenities_family: true,
        amenities_changing_facilities: false,
        amenities_disability_access: false,
        amenities_peaceful: true,
        amenities_electric_charging: false,
        amenities_no_restaurants: true,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: false,
        amenities_pet_friendly: true,
        amenities_forests: true,
        amenities_lots_of_wildlife: true,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: true,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: false,
        amenities_public_transport_bad: true,
        amenities_accommodation: false,
        amenities_wifi: false,
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1659962998/untrodden-pics/lickey_hills_y8xg8s.jpg",
        latitude: 52.489471,
        longitude: -2.898575,
        user_email: "untroddensoc@gmail.com"
    },
    {
        location_name: "Temple Newsam",
        street: "Temple Newsam Rd, ",
        town: "Leeds",
        region: "Yorkshire",
        postcode: " LS15 0AE",
        location_description: "Love temple newsam, great place to while away a few hours. Love the farm but never been in the house. Grounds and gardens are beautiful. Only thing that caused an issues was wasps, ice cream van and all the bins are full of them. There is also loads of free parking, only the car park by the house charges. If you have a max card, farm is also free. Loads of places for picnics and great pay ground for the kids.",
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1660143295/jd9vahliwcffeapg9nhr.jpg",
        latitude: 53.7845531667283,
        longitude: -1.5298391015316497,
        user_email: "untroddensoc@gmail.com",
        category_seaside: false,
        category_castles: false,
        category_caves: false,
        category_peaceful: false,
        category_hiking: false,
        category_hills: true,
        category_historic: false,
        category_secluded: false,
        category_casual: true,
        category_lakes: false,
        category_busy: true,
        category_woods: false,
        amenities_parking: true,
        amenities_food: true,
        amenities_family: true,
        amenities_changing_facilities: true,
        amenities_disability_access: true,
        amenities_peaceful: false,
        amenities_electric_charging: false,
        amenities_no_restaurants: false,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: false,
        amenities_pet_friendly: true,
        amenities_forests: true,
        amenities_lots_of_wildlife: false,
        amenities_watersports: false,
        amenities_shopping: true,
        amenities_bodies_of_water: false,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: true,
        amenities_public_transport_good: true,
        amenities_public_transport_bad: false,
        amenities_accommodation: false,
        amenities_wifi: false,
    },
    {
        location_name: "Beadnell Beach",
        street: "Harbour Road",
        town: "Beadnell",
        region: "North East",
        postcode: "NE76 5BW",
        location_description: "Beadnell Village is set at the end of a glorious stretch of beach known as Beadnell Bay. The Village is well known as one of the best equipped places in the County for watersports, with the beach lending itself well to surfing, kitesurfing, windsurfing, sailing, scuba diving.... the list goes on. \n\nThe Village's harbour lies at the North end of the bay and from there the beach, backed by huge dunes of sand, stretches South for miles. The sheer volume of holiday accommodation in Beadnell means that it is one of the most popular destinations for visitors on the coast. The Village itself is split, between the area around the harbour and the Village nearer the main road. The harbour area is distinctive as it is the only West-facing harbour on the East coast and has beautiful lime kilns that were built in the 18th Century.",
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1660143001/hfsv1kulcpigse5gfaou.jpg",
        latitude: 55.55150297753735,
        longitude: -1.6286238465827978,
        user_email: "untroddensoc@gmail.com",
        category_seaside: true,
        category_castles: false,
        category_caves: false,
        category_peaceful: true,
        category_hiking: false,
        category_hills: false,
        category_historic: false,
        category_secluded: true,
        category_casual: true,
        category_lakes: false,
        category_busy: false,
        category_woods: false,
        amenities_parking: true,
        amenities_food: false,
        amenities_family: true,
        amenities_changing_facilities: false,
        amenities_disability_access: false,
        amenities_peaceful: false,
        amenities_electric_charging: false,
        amenities_no_restaurants: false,
        amenities_museums: false,
        amenities_beach: true,
        amenities_hiking: false,
        amenities_pet_friendly: true,
        amenities_forests: false,
        amenities_lots_of_wildlife: false,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: true,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: false,
        amenities_public_transport_bad: true,
        amenities_accommodation: false,
        amenities_wifi: false,
    },
    {
        location_name: "New Forest Wildlife Park",
        street: "Deerleap Ln",
        town: "Southampton",
        region: "South West",
        postcode: "SO40 4UH",
        location_description: "The New Forest Wildlife Park (formerly The New Forest Otter, Owl and Wildlife Conservation Park) is located on the edge of The New Forest close to the towns of Ashurst and Lyndhurst. The park specialises in native and past-native wildlife of Britain and otters and owls from around the globe, housing four species of the former and ten of the latter.\n\nThe park is recognised as the UK's leading institution in the rescue and rehabilitation of sick, injured and orphaned wild otters, along with the rehabilitation of other wildlife such as owls, deer and foxes in similar situations, and it is involved in several conservation projects, including breeding programmes for endangered native species such as Scottish wildcats, water voles and harvest mice.",
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1660143233/ditxv2emnbm97rcwjcb6.jpg",
        latitude: 50.892043863769004,
        longitude: -1.5750171020888786,
        user_email: "untroddensoc@gmail.com",
        category_seaside: false,
        category_castles: false,
        category_caves: false,
        category_peaceful: true,
        category_hiking: false,
        category_hills: false,
        category_historic: false,
        category_secluded: false,
        category_casual: true,
        category_lakes: true,
        category_busy: false,
        category_woods: true,
        amenities_parking: true,
        amenities_food: true,
        amenities_family: true,
        amenities_changing_facilities: false,
        amenities_disability_access: true,
        amenities_peaceful: false,
        amenities_electric_charging: false,
        amenities_no_restaurants: false,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: true,
        amenities_pet_friendly: false,
        amenities_forests: false,
        amenities_lots_of_wildlife: true,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: false,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: false,
        amenities_public_transport_bad: false,
        amenities_accommodation: false,
        amenities_wifi: true,
    },
    {
        location_name: "Coed Y Brenin",
        street: "Coed Y Brenin Visitor Centre",
        town: "Ganllwyd, Dolgellau ",
        region: "North Wales",
        postcode: "LL40 2HZ",
        location_description: "Coed y Brenin (Welsh for King's Forest) is a forest in the Snowdonia National Park, North Wales near Dolgellau at grid reference SH7127. It is popular for its mountain bike trails and hiking paths. It has several man-made mountain bike singletrack courses in a woodland setting, varying in length from 12 to 38 km (7 to 23 mi), and one dual slalom course. ",
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1660143367/ofevvpqhwzqepugrffou.jpg",
        latitude: 52.82861418717141,
        longitude: -3.900279551053785,
        user_email: "untroddensoc@gmail.com",
        category_seaside: false,
        category_castles: false,
        category_caves: false,
        category_peaceful: false,
        category_hiking: true,
        category_hills: true,
        category_historic: false,
        category_secluded: false,
        category_casual: true,
        category_lakes: false,
        category_busy: false,
        category_woods: false,
        amenities_parking: true,
        amenities_food: true,
        amenities_family: true,
        amenities_changing_facilities: true,
        amenities_disability_access: true,
        amenities_peaceful: false,
        amenities_electric_charging: false,
        amenities_no_restaurants: false,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: false,
        amenities_pet_friendly: false,
        amenities_forests: true,
        amenities_lots_of_wildlife: true,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: false,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: false,
        amenities_public_transport_bad: false,
        amenities_accommodation: false,
        amenities_wifi: false,
    },
    {
        location_name: "White Cliffs of Dover",
        street: "Langdon Cliffs",
        town: "Upper Rd, Dover",
        region: "South East",
        postcode: "CT16 1HJ",
        location_description: "The White Cliffs of Dover now have a philosopher-in-residence to ponder why they are so important to the British. But what and who helped the chalk cliffs become such a symbol of the nation?\n\nFor many people the White Cliffs of Dover are a clear symbol of Britain in the way the Statue of Liberty defines America for many.\n\nSo much so, the National Trust has appointed a philosopher-in-residence to explore their importance to the nation. It owns a five-mile (8km) stretch of the famous Kent coastline and is fundraising to buy more.",
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1660143463/t2jo01dnvwfk5phiwzx3.jpg",
        latitude: 51.061097775223686,
        longitude: 1.3044534570240671,
        user_email: "untroddensoc@gmail.com",
        category_seaside: true,
        category_castles: false,
        category_caves: false,
        category_peaceful: true,
        category_hiking: true,
        category_hills: true,
        category_historic: true,
        category_secluded: false,
        category_casual: false,
        category_lakes: false,
        category_busy: false,
        category_woods: false,
        amenities_parking: true,
        amenities_food: false,
        amenities_family: false,
        amenities_changing_facilities: false,
        amenities_disability_access: false,
        amenities_peaceful: false,
        amenities_electric_charging: false,
        amenities_no_restaurants: true,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: false,
        amenities_pet_friendly: true,
        amenities_forests: false,
        amenities_lots_of_wildlife: true,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: true,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: false,
        amenities_public_transport_bad: true,
        amenities_accommodation: false,
        amenities_wifi: false,
    },
    {
        location_name: "Hunstanton Cliffs",
        street: "Cliff Parade",
        town: "Hunstanton",
        region: "East of England",
        postcode: "PE36  6EJ",
        location_description: "The famous red and white striped cliffs at Hunstanton are an eye-catching attraction. Have fun discovering the history and nature of the area by looking for creatures in the rock pools on the beach below or taking a leisurely stroll to view the old buildings perched on the cliff top.\n\nThe stripes are caused by the different types of rock.\n\nWhere the marker is is the top of the cliffs however further down near the old lighthouse is a public car park and a couple of cafes, a golf course and entrance to the beach. \n\nit is a lovely day out and the views over the cliffs are magnificent, highly recommended.",
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1660153066/uwqfqtomsfqge4jrkvjd.jpg",
        latitude: "52.94694806776721",
        longitude: "0.4907411602774516",
        user_email: "untroddensoc@gmail.com",
        category_seaside: true,
        category_castles: false,
        category_caves: false,
        category_peaceful: false,
        category_hiking: false,
        category_hills: true,
        category_historic: false,
        category_secluded: false,
        category_casual: true,
        category_lakes: false,
        category_busy: false,
        category_woods: false,
        amenities_parking: true,
        amenities_food: true,
        amenities_family: true,
        amenities_changing_facilities: false,
        amenities_disability_access: false,
        amenities_peaceful: false,
        amenities_electric_charging: false,
        amenities_no_restaurants: false,
        amenities_museums: false,
        amenities_beach: true,
        amenities_hiking: false,
        amenities_pet_friendly: true,
        amenities_forests: false,
        amenities_lots_of_wildlife: false,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: true,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: true,
        amenities_public_transport_bad: false,
        amenities_accommodation: true,
        amenities_wifi: false,
    },
    {
        location_name: "Yorkshire Dales National Park",
        street: "Bainbridge",
        town: "Leyburn",
        region: "Yorkshire",
        postcode: "DL8 3EL",
        location_description: "The Yorkshire Dales is an area of great natural beauty in Northern England, a large part of which has been designated as a national park. \n\nMuch of the landscape here is limestone country - lush green valleys (known locally as \"dales\") crested with white limestone cliffs (\"scars\") and limestone pavements cutting through wilder uplands beneath towering peaks of dark millstone grit. Throughout the dales, fields and pastures are bounded by distinctive drystone walls which criss-cross the hillsides in elaborate patterns; set against the limestone cliffs and escarpments these walls (which were originally built by sheep farmers in days gone by) look almost a natural part of the limestone scenery as viewed today.",
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1660143774/al4enrhipr5hyzfshire.jpg",
        latitude: 52.489471,
        longitude: -2.898575,
        user_email: "untroddensoc@gmail.com",
        category_seaside: false,
        category_castles: false,
        category_caves: false,
        category_peaceful: true,
        category_hiking: true,
        category_hills: true,
        category_historic: false,
        category_secluded: true,
        category_casual: false,
        category_lakes: true,
        category_busy: false,
        category_woods: true,
        amenities_parking: true,
        amenities_food: false,
        amenities_family: true,
        amenities_changing_facilities: false,
        amenities_disability_access: false,
        amenities_peaceful: false,
        amenities_electric_charging: false,
        amenities_no_restaurants: false,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: true,
        amenities_pet_friendly: true,
        amenities_forests: true,
        amenities_lots_of_wildlife: true,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: false,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: false,
        amenities_public_transport_bad: true,
        amenities_accommodation: false,
        amenities_wifi: false,
    },
    {
        location_id: 20,
        location_name: "Lyle Hill",
        street: "154 Lyle Rd,  ",
        town: "Greenock",
        region: "Central Scotland West",
        postcode: "PA16 7QU",
        location_description: "Took the opportunity on a sunny day to walk up to it from Gourock. It's a steep walk past some fabulous properties which took about 20 minutes. You can get up it by car from Greenock or Gourock. It's worth it for the view. Large anchor monument in memory of the French navy at the top. Not the most impressive viewing platform at the top but the views are amazing.\n\nGreat pubs nearby. cheap as chips drinks!",
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1660143722/f4zqvfttavz7hlflsjcr.jpg",
        latitude: 55.94495796020132,
        longitude: -4.787045230221992,
        user_email: "untroddensoc@gmail.com",
        category_seaside: true,
        category_castles: false,
        category_caves: false,
        category_peaceful: true,
        category_hiking: false,
        category_hills: false,
        category_historic: false,
        category_secluded: false,
        category_casual: true,
        category_lakes: false,
        category_busy: false,
        category_woods: false,
        amenities_parking: true,
        amenities_food: false,
        amenities_family: false,
        amenities_changing_facilities: true,
        amenities_disability_access: true,
        amenities_peaceful: false,
        amenities_electric_charging: false,
        amenities_no_restaurants: false,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: false,
        amenities_pet_friendly: false,
        amenities_forests: true,
        amenities_lots_of_wildlife: false,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: true,
        amenities_camping: false,
        amenities_mountains: true,
        amenities_hearing_loop: false,
        amenities_public_transport_good: false,
        amenities_public_transport_bad: true,
        amenities_accommodation: false,
        amenities_wifi: true,
    },
    {
        location_name: "B29 Over Exposed Crash Site",
        street: "Charlesworth",
        town: "Glossop",
        region: "East Midlands",
        postcode: "SK13 1JB",
        location_description: "ON NOVEMBER 3, 1948, A B-29 Superfortress crashed in the Peak District near Bleaklow.\n\nThe United States Airforce Boeing RB-29A was part of the 16th Photographic Reconnaissance Squadron. It had previously been used to photograph nuclear testing at Bikini Atoll, including the dropping of an atomic bomb. \n\nThe aircraft crashed near Higher Shelf Stones on Bleaklow during a routine daytime flight to the US Airforce Base in Warrington. It’s believed that the pilots thought they had passed the hills of Bleaklow, but due to low cloud cover their visibilty was obscured and the aircraft hit the ground a little over 2,000 feet above sea level. All 13 crew members were killed on impact.\n\nMuch of the wreckage remains on the moors to this day, along with an official memorial erected by the Royal Air Force Finningley in 1988. Sections of the wings and fuselage are still visible, along with gun turrets and Duplex-Cyclone engines. \n\nKnow Before You Go!\n\nThe grid reference for the site is SK 090949. Parking is often available at the layby on Snake Pass. There is a trail up to Bleaklow Head that can be followed to the trig point at Higher Shelf Stones, from there you can navigate to the site. It can be challenging to locate initially, but it's also visible on satellite maps. Be aware of weather conditions and the terrain on the moors when traveling. ",
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1660143662/mqm3s55ueglwewiodyky.jpg",
        latitude: 53.45076178825738,
        longitude: -1.8653864159074942,
        user_email: "untroddensoc@gmail.com",
        category_seaside: false,
        category_castles: false,
        category_caves: false,
        category_peaceful: true,
        category_hiking: true,
        category_hills: true,
        category_historic: false,
        category_secluded: true,
        category_casual: false,
        category_lakes: false,
        category_busy: false,
        category_woods: false,
        amenities_parking: true,
        amenities_food: false,
        amenities_family: false,
        amenities_changing_facilities: false,
        amenities_disability_access: false,
        amenities_peaceful: false,
        amenities_electric_charging: false,
        amenities_no_restaurants: true,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: true,
        amenities_pet_friendly: true,
        amenities_forests: false,
        amenities_lots_of_wildlife: false,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: false,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: false,
        amenities_public_transport_bad: true,
        amenities_accommodation: false,
        amenities_wifi: false,
    },
    {
        location_name: "Heads Of Ayr Farm Park",
        street: "Dunure Rd, Alloway",
        town: "Ayr ",
        region: "South West Scotland",
        postcode: "KA7 4LD",
        location_description: "Fun park with bumper boats, electric tractors, trampolines, quad biking, various animals & more. Great day out for the whole family. \n\nWe have plenty of exciting activities – Captain your own boat with our amazing bumper boats, soak your family and friends in water wars, try out our electric tractors and diggers, we even have a playpark, giant sand pit, trampolines, ringo sledging, a giant aerial runway and jumping pillows to keep you amused!\n\nCan get busy at peak time during school holidays.",
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1660144025/wcwwsiybrvpe2iev6eq9.jpg",
        latitude: 55.42556225621982,
        longitude: -4.690450016176044,
        user_email: "untroddensoc@gmail.com",
        category_seaside: false,
        category_castles: false,
        category_caves: false,
        category_peaceful: false,
        category_hiking: false,
        category_hills: false,
        category_historic: false,
        category_secluded: false,
        category_casual: true,
        category_lakes: false,
        category_busy: true,
        category_woods: false,
        amenities_parking: true,
        amenities_food: true,
        amenities_family: true,
        amenities_changing_facilities: true,
        amenities_disability_access: false,
        amenities_peaceful: false,
        amenities_electric_charging: false,
        amenities_no_restaurants: false,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: false,
        amenities_pet_friendly: false,
        amenities_forests: false,
        amenities_lots_of_wildlife: false,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: false,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: false,
        amenities_public_transport_bad: false,
        amenities_accommodation: false,
        amenities_wifi: false,
    },
    {
        location_name: "Museum of London",
        street: "150 London Wall",
        town: "Barbican",
        region: "London",
        postcode: "EC2Y 5HN",
        location_description: "The Museum of London documents the history of the UK's capital city from prehistoric to modern times. It is located in the City of London on the London Wall, close to the Barbican Centre and is part of the Barbican complex of buildings created in the 1960s and 1970s to redevelop a bomb-damaged area of the city. The museum is the largest urban history collection in the world, with more than six million objects.\n\nThe museum is a few minutes' walk north of St Paul's Cathedral, overlooking the remains of the Roman city wall and on the edge of the oldest part of London, now its main financial district. It is primarily concerned with the social history of London and its inhabitants throughout time. The museum is jointly controlled and funded by the City of London Corporation and the Greater London Authority.",
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1660144129/oumj5ztgk1tefup0qoou.jpg",
        latitude: 51.51713436754005,
        longitude: -0.1259027129144954,
        user_email: "untroddensoc@gmail.com",
        category_seaside: false,
        category_castles: false,
        category_caves: false,
        category_peaceful: false,
        category_hiking: false,
        category_hills: false,
        category_historic: true,
        category_secluded: false,
        category_casual: true,
        category_lakes: false,
        category_busy: true,
        category_woods: false,
        amenities_parking: true,
        amenities_food: true,
        amenities_family: true,
        amenities_changing_facilities: true,
        amenities_disability_access: false,
        amenities_peaceful: true,
        amenities_electric_charging: false,
        amenities_no_restaurants: false,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: false,
        amenities_pet_friendly: false,
        amenities_forests: false,
        amenities_lots_of_wildlife: false,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: false,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: true,
        amenities_public_transport_good: true,
        amenities_public_transport_bad: false,
        amenities_accommodation: false,
        amenities_wifi: true,
    },
    {
        location_name: "Thirlmere Infinity Pool",
        street: "Keswick",
        town: "Fisher Place",
        region: "North West",
        postcode: "CA12 4TN",
        location_description: "What an amazing find this was on a recent walk exploring waterfalls in the Lake District - a hidden infinity pool perched up high overlooking the Lake District mountains! There are loads of wild swimming spots in the Lake District - but not many gems like this that are high up a steep mountain side in a natural infinity pool setting with the best Lake District views. It was a stunning find and one of those 'wow' moments, where everything comes together - it was also quite deep for a good swim about.\n\nThis idyllic infinity pool is on the north-eastern side of Thirlmire in the Lake District in the highlighted circle on the map. It's not that long a walk from where you can park the car but the exact spot is a little hidden from the main path. By not sharing the exact location I think you'll enjoy this special place all the more when you discover it",
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1660144137/vt4savb1m0h70wgktren.jpg",
        latitude: 54.5545382193734,
        longitude: -3.0479123602657126,
        user_email: "untroddensoc@gmail.com",
        category_seaside: false,
        category_castles: false,
        category_caves: false,
        category_peaceful: false,
        category_hiking: true,
        category_hills: true,
        category_historic: false,
        category_secluded: true,
        category_casual: false,
        category_lakes: true,
        category_busy: false,
        category_woods: false,
        amenities_parking: true,
        amenities_food: false,
        amenities_family: false,
        amenities_changing_facilities: false,
        amenities_disability_access: false,
        amenities_peaceful: true,
        amenities_electric_charging: false,
        amenities_no_restaurants: true,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: true,
        amenities_pet_friendly: true,
        amenities_forests: false,
        amenities_lots_of_wildlife: false,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: true,
        amenities_camping: false,
        amenities_mountains: true,
        amenities_hearing_loop: false,
        amenities_public_transport_good: false,
        amenities_public_transport_bad: true,
        amenities_accommodation: false,
        amenities_wifi: false,
    },
    {
        location_name: "Birmingham Museum",
        street: "Chamberlain Sq,",
        town: " Birmingham ",
        region: "West Midlands",
        postcode: "B3 3DH",
        location_description: "Whenever I visit Birmingham I always visit Birmingham M&AG and it never disappoints.\nThe exhibitions are always thoughtfully and engagingly presented. There is a sense of inclusivity in this gallery that I have seldom experienced elsewhere.\nThe combination of works, old and new, by known and (as yet) less well-known artists in the Unprecedented Times exhibition was excellent. Great thrill to see a Cold War Steve original being exhibited. Que Club, Blacklash, We are Birmingham and Women in the City exhibitions are all well worth visiting.\nThe stand out piece for me was Beat Streuli's The Pallasades. Couldn't take my eyes of it. Simple yet moving.",
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1660144420/gwsacqcwgerslxipucjn.jpg",
        latitude: 52.41378712021037,
        longitude: -1.836988007634318,
        user_email: "untroddensoc@gmail.com",
        category_seaside: false,
        category_castles: false,
        category_caves: false,
        category_peaceful: true,
        category_hiking: false,
        category_hills: false,
        category_historic: true,
        category_secluded: false,
        category_casual: true,
        category_lakes: false,
        category_busy: false,
        category_woods: false,
        amenities_parking: false,
        amenities_food: false,
        amenities_family: false,
        amenities_changing_facilities: true,
        amenities_disability_access: true,
        amenities_peaceful: true,
        amenities_electric_charging: false,
        amenities_no_restaurants: true,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: false,
        amenities_pet_friendly: false,
        amenities_forests: false,
        amenities_lots_of_wildlife: false,
        amenities_watersports: false,
        amenities_shopping: true,
        amenities_bodies_of_water: false,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: true,
        amenities_public_transport_bad: false,
        amenities_accommodation: false,
        amenities_wifi: false,
    },
    {
        location_name: "Norwich Cathedral",
        street: "65 The Close",
        town: "Norwich",
        region: "East of England",
        postcode: "NR1 4DH",
        location_description: "Norwich Cathedral is an Anglican cathedral in Norwich, Norfolk, dedicated to the Holy and Undivided Trinity. It is the cathedral church for the Church of England Diocese of Norwich and is one of the Norwich 12 heritage sites. The cathedral was begun in 1096 and constructed out of flint and mortar and faced with a cream-coloured Caen limestone. An Anglo-Saxon settlement and two churches were demolished to make room for the buildings. The cathedral was completed in 1145 with the Norman tower still seen today topped with a wooden spire covered with lead. Episodes of damage necessitated rebuilding and the stone spire was erected in 1480. The bosses of Norwich Cathedral are one of the world's greatest mediaeval sculptural treasures that survived the iconoclasm of the Tudor and English Civil War periods.The bosses in the cloisters include hundreds that are carved and ornately painted. Norwich Cathedral has the second largest cloisters in England, only exceeded by those at Salisbury Cathedral. The cathedral close is one of the largest in Europe and has more people living within it than any other close",
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1660144560/rbnyylrqvbgn4fopzrea.jpg",
        latitude: 52.56146833411765,
        longitude: 1.2323658648492426,
        user_email: "untroddensoc@gmail.com",
        category_seaside: false,
        category_castles: true,
        category_caves: false,
        category_peaceful: false,
        category_hiking: false,
        category_hills: false,
        category_historic: true,
        category_secluded: false,
        category_casual: true,
        category_lakes: false,
        category_busy: true,
        category_woods: false,
        amenities_parking: true,
        amenities_food: true,
        amenities_family: true,
        amenities_changing_facilities: false,
        amenities_disability_access: true,
        amenities_peaceful: true,
        amenities_electric_charging: false,
        amenities_no_restaurants: false,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: false,
        amenities_pet_friendly: false,
        amenities_forests: false,
        amenities_lots_of_wildlife: false,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: false,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: true,
        amenities_public_transport_bad: false,
        amenities_accommodation: false,
        amenities_wifi: true,
    },
    {
        location_name: "Traeth Porthdinllaen",
        street: "Lon Golff, ",
        town: "Porthdinllaen, Pwllheli ",
        region: "North Wales",
        postcode: "LL53 6DB",
        location_description: "An old fishing village perched on the end of a thin ribbon of land stretching into the Irish Sea\nWith its clear sheltered waters lapping against stout stone houses, Porthdinllaen really is a jewel. You can watch fishermen bring in the daily catch while relaxing with a drink at the Tŷ Coch Inn.\n\nOr stay for longer in one of our holiday cottages and enjoy views across to Yr Eifl and Snowdonia whilst enjoying breakfast",
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1660144625/bhtlsy0bfi6thgwck75i.jpg",
        latitude: 52.94285180800071,
        longitude: -4.567720378582123,
        user_email: "untroddensoc@gmail.com",
        category_seaside: true,
        category_castles: false,
        category_caves: false,
        category_peaceful: true,
        category_hiking: true,
        category_hills: false,
        category_historic: false,
        category_secluded: true,
        category_casual: true,
        category_lakes: false,
        category_busy: false,
        category_woods: false,
        amenities_parking: false,
        amenities_food: true,
        amenities_family: true,
        amenities_changing_facilities: true,
        amenities_disability_access: false,
        amenities_peaceful: false,
        amenities_electric_charging: false,
        amenities_no_restaurants: false,
        amenities_museums: false,
        amenities_beach: true,
        amenities_hiking: true,
        amenities_pet_friendly: true,
        amenities_forests: false,
        amenities_lots_of_wildlife: false,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: true,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: false,
        amenities_public_transport_bad: false,
        amenities_accommodation: false,
        amenities_wifi: false,
    },
    {
        location_name: "Wemyss Caves",
        street: "3 Cave Cottages, ",
        town: "East Wemyss, Kirkcaldy",
        region: "Central Scotland East",
        postcode: "KY1 4RT",
        location_description: "My wife organised for us to visit here after finding out about it through Google. We both have an interest in Pictish and Scottish history, and to see all the carvings here was fascinating, the mystery around this place is gripping and leaves you wanting to find out more.\n\nOur guide Mike, part of the Save Wemyss Ancient Caves Society, was incredibly knowledgeable and enthusiastic about the area and its history, and helped us find every carving in the caves, as some are obscured by shadow or just hard to see without looking carefully. Some of the carvings, however, are large and very clear to see and elicit wonder and curiosity, to think what the person who carved it over 1000 years ago was thinking about.\n\nThe Caves and surroundings are deserving of more investment and interest in my opinion. There is a lot of history there, more so than some other heavily visited tourist attractions.\n\nThe visitor centre nearby has some great displays and information about the area too and is worth seeing.\n\nI highly recommend visiting, hopefully, the place will in time gain the popularity it deserves!",
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1660145106/q43pyetgfx3ebryh62e8.jpg",
        latitude: 56.181568950167616,
        longitude: -3.01471999028999,
        user_email: "untroddensoc@gmail.com",
        category_seaside: false,
        category_castles: false,
        category_caves: true,
        category_peaceful: true,
        category_hiking: false,
        category_hills: false,
        category_historic: true,
        category_secluded: false,
        category_casual: false,
        category_lakes: false,
        category_busy: false,
        category_woods: true,
        amenities_parking: false,
        amenities_food: false,
        amenities_family: false,
        amenities_changing_facilities: false,
        amenities_disability_access: false,
        amenities_peaceful: true,
        amenities_electric_charging: false,
        amenities_no_restaurants: true,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: true,
        amenities_pet_friendly: false,
        amenities_forests: true,
        amenities_lots_of_wildlife: false,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: false,
        amenities_camping: false,
        amenities_mountains: true,
        amenities_hearing_loop: false,
        amenities_public_transport_good: false,
        amenities_public_transport_bad: true,
        amenities_accommodation: false,
        amenities_wifi: false,
    },
    {
        location_name: "V and A Dundee",
        street: "1 Riverside Esplanade,",
        town: " Dundee ",
        region: "Central Scotland East",
        postcode: "DD1 4EZ",
        location_description: "What a welcome! From the moment we stepped through the door, we were met with smiles and warmth. We were given information about a workshop for children upstairs, and my daughter just loved it! Arts and crafts using Bauhaus themed motifs, and wonderful dressing up and dance, inspired by Bauhaus ballet. I think the museum has become much more child friendly since it was first built, and the downstairs space is much better utilised now, with activity tables welcoming you. This is better than the cafe space it previously was. A place you can visit every weekend with children - always something new to do, and what's more, it's free!",
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1660145100/coxsavktovb663tl6m1i.jpg",
        latitude: 56.45719445067451,
        longitude: -2.9670097786533347,
        user_email: "untroddensoc@gmail.com",
        category_seaside: false,
        category_castles: false,
        category_caves: false,
        category_peaceful: false,
        category_hiking: false,
        category_hills: false,
        category_historic: true,
        category_secluded: false,
        category_casual: true,
        category_lakes: false,
        category_busy: false,
        category_woods: false,
        amenities_parking: true,
        amenities_food: true,
        amenities_family: true,
        amenities_changing_facilities: true,
        amenities_disability_access: true,
        amenities_peaceful: false,
        amenities_electric_charging: false,
        amenities_no_restaurants: false,
        amenities_museums: true,
        amenities_beach: false,
        amenities_hiking: false,
        amenities_pet_friendly: false,
        amenities_forests: false,
        amenities_lots_of_wildlife: false,
        amenities_watersports: false,
        amenities_shopping: true,
        amenities_bodies_of_water: false,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: true,
        amenities_public_transport_good: false,
        amenities_public_transport_bad: true,
        amenities_accommodation: false,
        amenities_wifi: true,
    },
    {
        location_name: "Glen Affric Nature Reserve",
        street: "Glen Affric",
        town: "Cannich",
        region: "Scottish Highlands and Western Isles",
        postcode: "IV4 7LY",
        location_description: "Glen Affric is a magical mix of native woods, glistening lochs and haunting moorland. It features over 30 miles of ancient pinewoods and is one of the largest ancient Caledonian pine woods in Scotland. You can wander amongst the pine trees accompanied by the chirpy calls of woodland birds. Elsewhere you might encounter ospreys, secretive otters or red- and black-throated divers. Come in autumn and you’ll be inspired by the mosaic of colour and the echoing roar of red deer stags.\n\nBest Time To Visit: All year interest.\n\nFacilities: Several car parks with picnic tables, two seasonal toilets (one disabled), waymarked paths and Ranger service. An FCS guidemap is available. Camping, accommodation and shop in the nearby communities of Cannich and Tomich.",
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1660145374/jvffgqrgz8paxcqjivlh.jpg",
        latitude: 57.3046319196778,
        longitude: -4.866017855351515,
        user_email: "untroddensoc@gmail.com",
        category_seaside: false,
        category_castles: false,
        category_caves: false,
        category_peaceful: true,
        category_hiking: true,
        category_hills: false,
        category_historic: false,
        category_secluded: true,
        category_casual: true,
        category_lakes: true,
        category_busy: false,
        category_woods: true,
        amenities_parking: true,
        amenities_food: false,
        amenities_family: true,
        amenities_changing_facilities: false,
        amenities_disability_access: false,
        amenities_peaceful: true,
        amenities_electric_charging: false,
        amenities_no_restaurants: true,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: true,
        amenities_pet_friendly: true,
        amenities_forests: false,
        amenities_lots_of_wildlife: false,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: true,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: false,
        amenities_public_transport_bad: true,
        amenities_accommodation: false,
        amenities_wifi: false,
    },
    {
        location_name: "Tenby",
        street: "Tenby ",
        town: "Tenby",
        region: "South West Wales",
        postcode: "SA70 7BN",
        location_description: "Tenby is a harbour town and resort in southwest Wales. It’s known for its 13th-century town walls and its stretches of sandy shoreline, including Castle Beach. The ruins of Tenby Castle are on a headland overlooking the harbour. Exhibits at Tenby Museum and Art Gallery include a 16th-century wrought-iron cannon. The Tudor Merchant’s House recreates domestic life in 1500, with a merchant's shop and working kitchen.",
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1660146445/tumoqctaqgph1z9w6tot.jpg",
        latitude: 51.6715088127639,
        longitude: -4.702119076539589,
        user_email: "untroddensoc@gmail.com",
        category_seaside: true,
        category_castles: true,
        category_caves: false,
        category_peaceful: false,
        category_hiking: false,
        category_hills: false,
        category_historic: true,
        category_secluded: false,
        category_casual: false,
        category_lakes: false,
        category_busy: true,
        category_woods: false,
        amenities_parking: true,
        amenities_food: true,
        amenities_family: true,
        amenities_changing_facilities: true,
        amenities_disability_access: true,
        amenities_peaceful: false,
        amenities_electric_charging: false,
        amenities_no_restaurants: false,
        amenities_museums: true,
        amenities_beach: true,
        amenities_hiking: true,
        amenities_pet_friendly: true,
        amenities_forests: false,
        amenities_lots_of_wildlife: false,
        amenities_watersports: true,
        amenities_shopping: false,
        amenities_bodies_of_water: true,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: true,
        amenities_public_transport_bad: false,
        amenities_accommodation: false,
        amenities_wifi: false,
    },
    {
        location_name: "School of Code",
        street: "Custard Factory, Gibb St",
        town: "Birmingham",
        region: "West Midlands",
        postcode: "B9 4AA",
        location_description: "School of Code offers free intensive and flexible coding courses open to applicants of all backgrounds.\n\nYou don’t need to have any previous technical experience or any qualifications. All you need is motivation, and to like solving problems!\n\nSchool of Code's purpose is to give everyone a route into technology, and teach them the skills they need to leap into the industry.\n\nThe rise in automation will have a dramatic impact on the job market. We aim to prepare people with the tech skills and soft skills to become collaborative, creative coders.\n\nSo far, we've achieved an average of 85% employment from our previous cohorts (including during the COVID-19 pandemic). But, more important than stats, we've helped people completely change their lives for the better.",
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1660144769/xaufqhlvr3wbaeyueqdz.png",
        latitude: 52.47521026929371,
        longitude: -1.8841853252084206,
        user_email: "untroddensoc@gmail.com",
        category_seaside: false,
        category_castles: false,
        category_caves: false,
        category_peaceful: false,
        category_hiking: false,
        category_hills: false,
        category_historic: false,
        category_secluded: false,
        category_casual: false,
        category_lakes: false,
        category_busy: true,
        category_woods: false,
        amenities_parking: false,
        amenities_food: false,
        amenities_family: false,
        amenities_changing_facilities: false,
        amenities_disability_access: true,
        amenities_peaceful: false,
        amenities_electric_charging: false,
        amenities_no_restaurants: false,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: false,
        amenities_pet_friendly: false,
        amenities_forests: false,
        amenities_lots_of_wildlife: false,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: false,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: true,
        amenities_public_transport_bad: false,
        amenities_accommodation: false,
        amenities_wifi: true,
    }
]

export default locations;