const locations = [
    {
        location_name: "Old Pale",
        street: "Delamere Forest",
        town: "Delamere",
        region: "North West",
        postcode: "CW8 2HZ",
        location_description: "Using forest gravelled tracks and purpose-built stoned paths up the hill you will be rewarded by enormous skies and an endless view. There are plenty of benches along the route to encourage you to stop and take it all in. With hourly trains from Manchester and Chester, Delamere Forest and the Old Pale walk is a great place to explore at any time of year.",
        category_seaside: false,
        category_castles: false,
        category_caves: false,
        category_peaceful: true,
        category_hiking: false,
        category_hills: true,
        category_historic: false,
        category_secluded: true,
        category_casual: true,
        category_lakes: false,
        category_busy: false,
        category_woods: true,
        amenities_parking: true,
        amenities_food: true,
        amenities_family: true,
        amenities_changing_facilities: false,
        amenities_disability_access: true,
        amenities_peaceful: true,
        amenities_electric_charging: false,
        amenities_no_restaurants: false,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: false,
        amenities_pet_friendly: true,
        amenities_forests: false,
        amenities_lots_of_wildlife: true,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: false,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: true,
        amenities_public_transport_bad: false,
        amenities_accommodation: false,
        amenities_wifi: false,
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1659962631/untrodden-pics/old_pale_rwsbbp.jpg",
        latitude:  53.22376473032904, 
        longitude: -2.6849296015820943,
        user_email: "untroddensoc@gmail.com"
    },
    {
        location_name: "Dunnottar Castle",
        street: "Dunnottar Castle",
        town: "Stonehaven",
        region: "North East Scotland",
        postcode: "AB39 2TL",
        location_description: "Dunnottar Castle is a dramatic and evocative ruined cliff top fortress which was the home of the Earls Marischal, once one of the most powerful families in Scotland. Steeped in history, this romantic and haunting ruin is a photographer's paradise, a history lovers dream and an iconic tourist destination for visitors the world over. Visit Dunnottar Castle for your own unforgettable experience and discover the importance of Dunnottar - an impregnable fortress that holds many rich secrets of Scotland's colourful past.",
        category_seaside: true,
        category_castles: true,
        category_caves: false,
        category_peaceful: true,
        category_hiking: true,
        category_hills: true,
        category_historic: true,
        category_secluded: true,
        category_casual: true,
        category_lakes: false,
        category_busy: false,
        category_woods: false,
        amenities_parking: true,
        amenities_food: true,
        amenities_family: true,
        amenities_changing_facilities: true,
        amenities_disability_access: true,
        amenities_peaceful: true,
        amenities_electric_charging: false,
        amenities_no_restaurants: false,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: true,
        amenities_pet_friendly: true,
        amenities_forests: false,
        amenities_lots_of_wildlife: false,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: true,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: true,
        amenities_public_transport_bad: false,
        amenities_accommodation: false,
        amenities_wifi: false,
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1659962631/untrodden-pics/dunnottar_castle_fm0vft.jpg",
        latitude:  56.945395623234326, 
        longitude: -2.1978927412285247,
        user_email: "untroddensoc@gmail.com"
    },
    {
        location_name: "Symonds Yat",
        street: "",
        town: "Symonds Yat",
        region: "West Midlands",
        postcode: "HR9",
        location_description: "Symonds Yat is a village in the Wye Valley and a popular tourist destination, straddling the River Wye in the English county of Herefordshire, close to the Gloucestershire border. It is within a few miles of Monmouthshire and the Welsh border.",
        category_seaside: false,
        category_castles: false,
        category_caves: false,
        category_peaceful: true,
        category_hiking: true,
        category_hills: true,
        category_historic: false,
        category_secluded: false,
        category_casual: true,
        category_lakes: true,
        category_busy: false,
        category_woods: true,
        amenities_parking: true,
        amenities_food: true,
        amenities_family: true,
        amenities_changing_facilities: true,
        amenities_disability_access: true,
        amenities_peaceful: true,
        amenities_electric_charging: true,
        amenities_no_restaurants: false,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: true,
        amenities_pet_friendly: true,
        amenities_forests: true,
        amenities_lots_of_wildlife: true,
        amenities_watersports: true,
        amenities_shopping: true,
        amenities_bodies_of_water: true,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: true,
        amenities_public_transport_bad: false,
        amenities_accommodation: true,
        amenities_wifi: true,
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1659962631/untrodden-pics/symonds_yat_aymseo.jpg",
        latitude: 51.84645761540501,
        longitude: -2.6461539072289497,
        user_email: "untroddensoc@gmail.com"
    },
    {
        location_name: "Foggintor Quarry",
        street: "Foggintor Quarry",
        town: "Yelverton",
        region: "South West",
        postcode: "PL20 6SS",
        location_description: "For more than a hundred years, Foggintor Quarry was one of three great Dartmoor granite quarries, providing the stone for famous landmarks.",
        category_seaside: false,
        category_castles: false,
        category_caves: false,
        category_peaceful: true,
        category_hiking: true,
        category_hills: true,
        category_historic: true,
        category_secluded: true,
        category_casual: true,
        category_lakes: true,
        category_busy: false,
        category_woods: true,
        amenities_parking: true,
        amenities_food: false,
        amenities_family: true,
        amenities_changing_facilities: false,
        amenities_disability_access: false,
        amenities_peaceful: true,
        amenities_electric_charging: false,
        amenities_no_restaurants: true,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: true,
        amenities_pet_friendly: true,
        amenities_forests: true,
        amenities_lots_of_wildlife: true,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: true,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: false,
        amenities_public_transport_bad: true,
        amenities_accommodation: false,
        amenities_wifi: false,
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1659962632/untrodden-pics/foggintor_quarry_gsjnkd.jpg",
        latitude: 50.54478107930167,
        longitude: -4.024222293115765,
        user_email: "untroddensoc@gmail.com"
    },
    {
        location_name: "Solomon's Tower",
        street: "Green Lane",
        town: "Buxton",
        region: "East Midlands",
        postcode: "SK17 9DH",
        location_description: "Solomon's Temple, also known as Grin Low Tower, is a Victorian fortified hill marker at the summit of Grin Low Hill near the spa town of Buxton. At 439 metres above sea-level, the views from the top of this modest tower are not-to-be-missed and on a clear day it's possible to see Mam Tor in Castleton and Kinder Scout - the highest point in the Peak District!",
        category_seaside: false,
        category_castles: true,
        category_caves: false,
        category_peaceful: true,
        category_hiking: true,
        category_hills: true,
        category_historic: true,
        category_secluded: true,
        category_casual: true,
        category_lakes: false,
        category_busy: false,
        category_woods: true,
        amenities_parking: true,
        amenities_food: false,
        amenities_family: true,
        amenities_changing_facilities: false,
        amenities_disability_access: false,
        amenities_peaceful: true,
        amenities_electric_charging: false,
        amenities_no_restaurants: true,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: true,
        amenities_pet_friendly: true,
        amenities_forests: true,
        amenities_lots_of_wildlife: true,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: false,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: true,
        amenities_public_transport_bad: false,
        amenities_accommodation: false,
        amenities_wifi: false,
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1659962630/untrodden-pics/solomons_tower_umzn1w.jpg",
        latitude: 53.242709,
        longitude: -1.920569,
        user_email: "untroddensoc@gmail.com"
    },
    {
        location_name: "Marchmont Community Garden",
        street: "Marchmont Street",
        town: "London",
        region: "London",
        postcode: "WC1N 1NJ",
        location_description: "This is a pocket park in Bloomsbury next to the Brunswick Centre that was once a private garden and fenced off, but just over a decade ago was opened up as a public space.",
        category_seaside: false,
        category_castles: false,
        category_caves: false,
        category_peaceful: true,
        category_hiking: false,
        category_hills: false,
        category_historic: false,
        category_secluded: true,
        category_casual: true,
        category_lakes: false,
        category_busy: false,
        category_woods: false,
        amenities_parking: false,
        amenities_food: true,
        amenities_family: true,
        amenities_changing_facilities: false,
        amenities_disability_access: true,
        amenities_peaceful: true,
        amenities_electric_charging: false,
        amenities_no_restaurants: false,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: false,
        amenities_pet_friendly: true,
        amenities_forests: false,
        amenities_lots_of_wildlife: false,
        amenities_watersports: false,
        amenities_shopping: true,
        amenities_bodies_of_water: false,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: true,
        amenities_public_transport_bad: false,
        amenities_accommodation: false,
        amenities_wifi: false,
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1659962638/untrodden-pics/marchmont_garden_lkoh4o.jpg",
        latitude: 51.525098,
        longitude: -0.124815,
        user_email: "untroddensoc@gmail.com"
    },
    {
        location_name: "Harborne Walkway",
        street: "Harborne Walkway",
        town: "Birmingham",
        region: "West Midlands",
        postcode: "B16 0SL",
        location_description: "The Harborne Walkway is a 1.5 mile stretch which runs from Forest Drive and Park Hill Road Harborne entrances to Summerfield Park. It is a linear park and the responsibility of the Council Parks Department. It passes by allotments and the Harborne Bird Sanctuary following the old railway line. It’s a nice atmospheric stroll with shady woodland, embankments, wide verges and across or under 6 bridges. The path is well surfaced and forms part of an easy route, safe for cyclists and walkers, which carries on into Summerfield Park.",
        category_seaside: false,
        category_castles: false,
        category_caves: false,
        category_peaceful: true,
        category_hiking: true,
        category_hills: false,
        category_historic: false,
        category_secluded: true,
        category_casual: true,
        category_lakes: false,
        category_busy: false,
        category_woods: true,
        amenities_parking: false,
        amenities_food: false,
        amenities_family: true,
        amenities_changing_facilities: false,
        amenities_disability_access: true,
        amenities_peaceful: true,
        amenities_electric_charging: false,
        amenities_no_restaurants: true,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: true,
        amenities_pet_friendly: true,
        amenities_forests: true,
        amenities_lots_of_wildlife: true,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: false,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: true,
        amenities_public_transport_bad: false,
        amenities_accommodation: false,
        amenities_wifi: false,
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1659962640/untrodden-pics/harborne_walkway_i8kuqh.jpg",
        latitude: 52.481151,
        longitude: -1.943754,
        user_email: "untroddensoc@gmail.com"
    },
    {
        location_name: "Horgabost Beach",
        street: "Horgabost",
        town: "Isle of Harris",
        region: "Outer Hebrides",
        postcode: "HS3 3HR",
        location_description: "Horgabost is yet another stunning white sandy Hebridean beach. Located on South Harris, this beach is just around the corner from better known Luskentyre beach. Horgabost shares the same crystal clear green blue water and pristine sands but is slightly more sheltered. The beach looks straight out over the Sound of Taransay with the mountains beyond forming a spectacular backdrop. It is from Horgabost that you can take a boat trip out into the sound. Like other Harris Isle beaches the meadows leading down to the coast become carpeted in wildflowers during the summer months. This is known as ‘machair’ locally. Whilst there are no facilities on the beach per se, there is a campsite within a stone’s throw with a shop and toilets.",
        category_seaside: true,
        category_castles: false,
        category_caves: false,
        category_peaceful: true,
        category_hiking: false,
        category_hills: false,
        category_historic: false,
        category_secluded: true,
        category_casual: true,
        category_lakes: false,
        category_busy: false,
        category_woods: false,
        amenities_parking: true,
        amenities_food: false,
        amenities_family: true,
        amenities_changing_facilities: false,
        amenities_disability_access: false,
        amenities_peaceful: false,
        amenities_electric_charging: false,
        amenities_no_restaurants: true,
        amenities_museums: false,
        amenities_beach: true,
        amenities_hiking: false,
        amenities_pet_friendly: true,
        amenities_forests: false,
        amenities_lots_of_wildlife: false,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: false,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: false,
        amenities_public_transport_bad: true,
        amenities_accommodation: false,
        amenities_wifi: false,
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1659962629/untrodden-pics/horgabost_beach_tox6yr.jpg",
        latitude: 57.86451376037841,
        longitude: -6.985501206854588,
        user_email: "untroddensoc@gmail.com"
    },
    {
        location_name: "Radnor Castle Mound",
        street: "11 High St, New Radnor",
        town: "Presteigne",
        region: "Mid Wales",
        postcode: "LD8 2SL",
        location_description: "An old castle mound in the Welsh hills. Radnor (Welsh: Maesyfed) is a village in Powys, Wales, to the south of Radnor Forest, and was the county town of Radnorshire. Attractions in the town include a significant castle [1] mound of a Norman motte [2]. New Radnor castle was originally called Trefaesyfed and was once a considerable fortress and a significant border castle in the Welsh Marches and played its part in the turmoil, violence and barbarity of the early medieval period typical of such a site.",
        category_seaside: false,
        category_castles: true,
        category_caves: false,
        category_peaceful: false,
        category_hiking: false,
        category_hills: false,
        category_historic: false,
        category_secluded: false,
        category_casual: false,
        category_lakes: false,
        category_busy: false,
        category_woods: false,
        amenities_parking: true,
        amenities_food: false,
        amenities_family: true,
        amenities_changing_facilities: false,
        amenities_disability_access: false,
        amenities_peaceful: true,
        amenities_electric_charging: false,
        amenities_no_restaurants: true,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: true,
        amenities_pet_friendly: true,
        amenities_forests: false,
        amenities_lots_of_wildlife: false,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: false,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: false,
        amenities_public_transport_bad: true,
        amenities_accommodation: false,
        amenities_wifi: false,
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1659962631/untrodden-pics/radnor_castle_mound_ft8poh.jpg",
        latitude: 52.24158189495012,
        longitude: -3.1556172471674757,
        user_email: "untroddensoc@gmail.com"
        
    },
    {
        location_name: "Glenoe Waterfall",
        street: "Waterfall Rd",
        town: "Gleno",
        region: "Antrim",
        postcode: "BT40 3LE",
        location_description: "Glenoe is a magnificent 30 foot waterfall nestling in the glens of Antrim and owned by the National Trust. It is such a charming place and I can’t believe that we did not know of its existence. Th walk up the narrow path up through the glen is superb (although you will definitely need walking boots and moderate fitness as it is steep enough). It is worth calling by though just to stroll over to the waterfall – this is a short level path and you will definitely want to take some photos. We visited in early March – magical greens – lots of mosses and ferns. Birds song added to the atmosphere. A perfect starter to a day in the Antrim glens. ",
        category_seaside: false,
        category_castles: false,
        category_caves: false,
        category_peaceful: true,
        category_hiking: true,
        category_hills: true,
        category_historic: false,
        category_secluded: true,
        category_casual: true,
        category_lakes: false,
        category_busy: false,
        category_woods: true,
        amenities_parking: false,
        amenities_food: false,
        amenities_family: true,
        amenities_changing_facilities: false,
        amenities_disability_access: false,
        amenities_peaceful: true,
        amenities_electric_charging: false,
        amenities_no_restaurants: true,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: true,
        amenities_pet_friendly: true,
        amenities_forests: true,
        amenities_lots_of_wildlife: true,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: false,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: true,
        amenities_public_transport_bad: false,
        amenities_accommodation: false,
        amenities_wifi: false,
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1659962630/untrodden-pics/glenoe_waterfall_nqqgpg.jpg",
        latitude: 54.799441382524805,
        longitude: -5.832403748657128,
        user_email: "untroddensoc@gmail.com"
    },
    {
        location_name: "Coney Island",
        street: "Kinnego Marina",
        town: "Oxford island",
        region: "Armagh",
        postcode: "BT66 6N",
        location_description: "Lying 1km off shore from Maghery Country Park, this island is an exciting destination to be explored. The island has a rich history spanning many centuries, with evidence of human occupation dating back 8000 years BC. One of the most westerly outposts of the Normans during their occupation of Ireland from 12th Century. The island is owned by the National Trust. Regular Boat Trips are no longer available due to passenger boats being unable to dock at Maghery Country Park. Pre-booked groups of 6-12 persons can avail of a boat trip from Kinnego Marina, May to August weather permitting on a Wednesday, Thursday or Friday morning only. This is a 3 hour round trip and booking is essential.",
        category_seaside: false,
        category_castles: false,
        category_caves: false,
        category_peaceful: true,
        category_hiking: false,
        category_hills: false,
        category_historic: true,
        category_secluded: true,
        category_casual: true,
        category_lakes: false,
        category_busy: false,
        category_woods: true,
        amenities_parking: false,
        amenities_food: false,
        amenities_family: true,
        amenities_changing_facilities: false,
        amenities_disability_access: false,
        amenities_peaceful: true,
        amenities_electric_charging: false,
        amenities_no_restaurants: true,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: false,
        amenities_pet_friendly: true,
        amenities_forests: true,
        amenities_lots_of_wildlife: true,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: true,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: false,
        amenities_public_transport_bad: true,
        amenities_accommodation: false,
        amenities_wifi: false,
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1659962628/untrodden-pics/coney_island_w3gcu8.jpg",
        latitude: 54.51692011833266,
        longitude: -6.550751071994922,
        user_email: "untroddensoc@gmail.com"
    },
    {
        location_name: "Swanage beach",
        street: "1 Shore Road",
        town: "Swanage",
        region: "West Midlands",
        postcode: "BH19 1L",
        location_description: "The sandy beach is one of the main attractions of the town. The waters are clean, and the beach has won many European Blue Flag Awards, as well as the Seaside Award. Swanage beach has a well earned reputation for being a good place to soak up the sun and play in the sand and sea.\n\nDeck chairs are available for hire, as are pedaloes, kayaks and sun beds. The beach runs the length of the town and is backed by a promenade lined with amusements and attractions. It is found on the South West Coast Path.\n\nDiver training and excursions run regularly from Swanage. Other water sports include sailing, water-skiing and wind surfing.\n\nAn attractive promenade (which is partly pedestrianised during the summer months) runs along a stretch of the beach.\n",
        category_seaside: true,
        category_castles: false,
        category_caves: false,
        category_peaceful: false,
        category_hiking: true,
        category_hills: false,
        category_historic: false,
        category_secluded: false,
        category_casual: false,
        category_lakes: false,
        category_busy: false,
        category_woods: false,
        amenities_parking: true,
        amenities_food: false,
        amenities_family: false,
        amenities_changing_facilities: false,
        amenities_disability_access: false,
        amenities_peaceful: false,
        amenities_electric_charging: false,
        amenities_no_restaurants: false,
        amenities_museums: true,
        amenities_beach: false,
        amenities_hiking: false,
        amenities_pet_friendly: false,
        amenities_forests: false,
        amenities_lots_of_wildlife: false,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: false,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: false,
        amenities_public_transport_bad: false,
        amenities_accommodation: false,
        amenities_wifi: false,
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1659962998/untrodden-pics/swanage_beach_ih9ppi.jpg",
        latitude: 52.489471,
        longitude: -2.898575,
        user_email: "untroddensoc@gmail.com"
    },
    {
        location_name: "Lickey Hills",
        street: "Warren Ln, Rednal, Birmingham",
        town: "Birmingham",
        region: "West Midlands",
        postcode: "B45 8ER",
        location_description: "Lovely woods with a beautiful view of Birmingham. Originally donated to Birmingham council by The Cadbury brothers to preserve Birmingham's woods and green spaces. Good parking and a visitors centre with toilets and a café. Large woodlands with hills, paths and a kids playground.\n\nGood public transport links and a couple of pubs nearby if you want to hydrate after a long walk!",
        category_seaside: false,
        category_castles: false,
        category_caves: false,
        category_peaceful: true,
        category_hiking: false,
        category_hills: true,
        category_historic: true,
        category_secluded: true,
        category_casual: true,
        category_lakes: false,
        category_busy: false,
        category_woods: true,
        amenities_parking: false,
        amenities_food: false,
        amenities_family: true,
        amenities_changing_facilities: false,
        amenities_disability_access: false,
        amenities_peaceful: true,
        amenities_electric_charging: false,
        amenities_no_restaurants: true,
        amenities_museums: false,
        amenities_beach: false,
        amenities_hiking: false,
        amenities_pet_friendly: true,
        amenities_forests: true,
        amenities_lots_of_wildlife: true,
        amenities_watersports: false,
        amenities_shopping: false,
        amenities_bodies_of_water: true,
        amenities_camping: false,
        amenities_mountains: false,
        amenities_hearing_loop: false,
        amenities_public_transport_good: false,
        amenities_public_transport_bad: true,
        amenities_accommodation: false,
        amenities_wifi: false,
        image_url: "https://res.cloudinary.com/dnshrtqmv/image/upload/v1659962998/untrodden-pics/lickey_hills_y8xg8s.jpg",
        latitude: 52.489471,
        longitude: -2.898575,
        user_email: "untroddensoc@gmail.com"
    }
]

export default locations;